// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * UserInfo - site user API response payload structure
 */
export class UserInfo {
    /**
     * Creates a new UserInfo instance.
     * @param {Partial<UserInfo>} [$$source = {}] - The source object to create the UserInfo.
     */
    constructor($$source = {}) {
        if (!("Email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Email"] = "";
        }
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Id"] = 0;
        }
        if (!("IsHiddenInUI" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsHiddenInUI"] = false;
        }
        if (!("IsSiteAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsSiteAdmin"] = false;
        }
        if (!("LoginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LoginName"] = "";
        }
        if (!("PrincipalType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PrincipalType"] = 0;
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserInfo(/** @type {Partial<UserInfo>} */($$parsedSource));
    }
}
