// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class StampingItem {
    /**
     * Creates a new StampingItem instance.
     * @param {Partial<StampingItem>} [$$source = {}] - The source object to create the StampingItem.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Id"] = 0;
        }
        if (!("CreationDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreationDate"] = "";
        }
        if (!("Selected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Selected"] = false;
        }
        if (!("StagedforFiling" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["StagedforFiling"] = false;
        }
        if (!("StampText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StampText"] = "";
        }
        if (!("SubmitterName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SubmitterName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StampingItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StampingItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StampingItem(/** @type {Partial<StampingItem>} */($$parsedSource));
    }
}
