// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * OpenPreferencePane opens the preference pane
 * @returns {Promise<application$0.WebviewWindow | null> & { cancel(): void }}
 */
export function OpenPreferencePane() {
    let $resultPromise = /** @type {any} */($Call.ByID(3737651544));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SetPreference sets a preference
 * @param {string} key
 * @param {string} value
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetPreference(key, value) {
    let $resultPromise = /** @type {any} */($Call.ByID(3142286532, key, value));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = application$0.WebviewWindow.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
