// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../github.com/koltyakov/gosip/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Download the unstamped attachment
 * @param {number} id
 * @returns {Promise<string> & { cancel(): void }}
 */
export function DownloadAttachment(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(1848096895, id));
    return $resultPromise;
}

/**
 * @returns {Promise<$models.StampingItem[]> & { cancel(): void }}
 */
export function LoadUnstamped() {
    let $resultPromise = /** @type {any} */($Call.ByID(2483799793));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<api$0.UserInfo | null> & { cancel(): void }}
 */
export function SignIn() {
    let $resultPromise = /** @type {any} */($Call.ByID(3045672228));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Upload the stamped attachment
 * @param {number} id
 * @param {string} stamped
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UploadStamped(id, stamped) {
    let $resultPromise = /** @type {any} */($Call.ByID(3259091991, id, stamped));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.StampingItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = api$0.UserInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
